sudo: required

language: php

php:
  - '7.0'

services:
  - mysql

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - php5-fpm
      - php5-mysql
      - nginx
    
hosts:
  - site.localhost

before_install:
  - export PATH=vendor/bin:$PATH
  - mysql -e "CREATE DATABASE IF NOT EXISTS hng;" -u root
  - mysql -e "CREATE USER 'hng'@'localhost' IDENTIFIED BY 'hng';" -u root
  - mysql -e "GRANT ALL PRIVILEGES ON hng.* TO 'hng'@'localhost';" -u root
  - mysql -e "FLUSH PRIVILEGES;" -u root

install:
  - composer install --prefer-dist
  - sudo cp deploy/vconf.conf /etc/nginx/sites-available/$SITE_DOMAIN
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$TRAVIS_BUILD_DIR?g" --in-place /etc/nginx/sites-available/$SITE_DOMAIN
  - sudo sed -e "s?%SITE_DOMAIN%?$SITE_DOMAIN?g" --in-place /etc/nginx/sites-available/$SITE_DOMAIN
  - sudo ln -s /etc/nginx/sites-available/$SITE_DOMAIN /etc/nginx/sites-enabled/

before_script:
  - sudo service php5-fpm restart
  - sudo service nginx restart

script:
 - curl http://site.localhost
 
after_success: 
- chmod +x ./push.sh 
- ./push.sh

env:
  global:
    - SITE_URL="http://site.localhost"
    - SITE_DOMAIN="site.localhost"
    - FOLDER="/var/www/HNGFun"
    - DB_NAME="hngfun"
    - secure: ImjFaoYXxdUIJ2/R0r9HWRcJJloQFyAaMDcLhJUQMY5wlEbncrWmEGFq46rTTe0+cr6/52U5moU/hfygEf/J6CpNR6K2OL9u/KuC57w38ui8uUb7r6RaurO7sZRLF3SMPUDXPkCZUn4raJ05wxy3uu6xGByXZKUjBXAS2VP3wTLXkfNz0VivkOVb2DAVMybS5dRYuOarClTbOZud4KfAty8HuXE6iS7iOkpWSMoaZj3truRXrZR1ZMBQMUvWcA2TKRyr1w1RE1BhuJtIIWGUAEjP+rVEDrcC/igMJ+mlQrEQNbaaf5gS4dL8oac15uWepkB5/TJhQm+TbkdjthfhLcLxV22v2CgarbgcnZpiifU5nP5Ppk+Q2pbi1Y7v2Wa9Ju3QMBkCRiStSMlrBmubPP76a+RfMkEuWLul07esCwQxT/EHs94TnmCgcJFlFfUANZQu4moApkxWXa7lRdiNiA0bbyC1ISFvNryOlJyRqbY2gfWhn/xHi3ZWTQSWpSTW/5gsU8znQrPEPG+hTjFVV3pUIHt+ShENY0gQ5F2acfyFRa7uP1HCdN/Mqa2H3UcSb7YMcwhM4vRE+Sapr21MzZ4buZ91GZRGeM7riQTcHD00Zm5ppQQ8MU4ZqL+SXi3S4UKw4Dno1HrxhoyCqOYgx5vNGM5/1wCgahIWmNTnYEE=
